using Shapes2D;
using UIForia.Layout;
using UIForia.Layout.LayoutTypes;
using TMPro;
using System.Collections.Generic;
using UnityEngine;
using UIForia.Util;
using UIForia.Text;
using FontStyle = UIForia.Text.FontStyle;
using TextAlignment = UIForia.Text.TextAlignment;

// Do not edit this file. See CodeGen.cs instead.

namespace UIForia.Rendering {

    public static class DefaultStyleValues_Generated {

		public const Overflow OverflowX = UIForia.Rendering.Overflow.None;
		public const Overflow OverflowY = UIForia.Rendering.Overflow.None;
		public static readonly Color BorderColor = new Color(-1f, -1f, -1f, -1f);
		public static readonly Color BackgroundColor = new Color(-1f, -1f, -1f, -1f);
		public static readonly Color BackgroundColorSecondary = new Color(-1f, -1f, -1f, -1f);
		public static readonly Texture2D BackgroundImage = null;
		public static readonly Texture2D BackgroundImage1 = null;
		public static readonly Texture2D BackgroundImage2 = null;
		public const GradientType BackgroundGradientType = Shapes2D.GradientType.Linear;
		public const GradientAxis BackgroundGradientAxis = Shapes2D.GradientAxis.Horizontal;
		public const float BackgroundGradientStart = 0;
		public const float BackgroundFillRotation = 0;
		public const BackgroundFillType BackgroundFillType = UIForia.Rendering.BackgroundFillType.Normal;
		public const BackgroundShapeType BackgroundShapeType = UIForia.Rendering.BackgroundShapeType.Rectangle;
		public const float BackgroundFillOffsetX = 0;
		public const float BackgroundFillOffsetY = 0;
		public const float BackgroundFillScaleX = 1;
		public const float BackgroundFillScaleY = 1;
		public const float Opacity = 1;
		public static readonly Texture2D Cursor = null;
		public const Visibility Visibility = UIForia.Rendering.Visibility.Visible;
		public const int FlexItemOrder = 0;
		public const int FlexItemGrow = 0;
		public const int FlexItemShrink = 0;
		public const CrossAxisAlignment FlexItemSelfAlignment = UIForia.Layout.CrossAxisAlignment.Unset;
		public const LayoutDirection FlexLayoutDirection = UIForia.Rendering.LayoutDirection.Row;
		public const LayoutWrap FlexLayoutWrap = UIForia.Rendering.LayoutWrap.None;
		public const MainAxisAlignment FlexLayoutMainAxisAlignment = UIForia.Layout.MainAxisAlignment.Start;
		public const CrossAxisAlignment FlexLayoutCrossAxisAlignment = UIForia.Layout.CrossAxisAlignment.Start;
		public const int GridItemColStart = 2147483647;
		public const int GridItemColSpan = 1;
		public const int GridItemRowStart = 2147483647;
		public const int GridItemRowSpan = 1;
		public const CrossAxisAlignment GridItemColSelfAlignment = UIForia.Layout.CrossAxisAlignment.Unset;
		public const CrossAxisAlignment GridItemRowSelfAlignment = UIForia.Layout.CrossAxisAlignment.Unset;
		public const LayoutDirection GridLayoutDirection = UIForia.Rendering.LayoutDirection.Row;
		public const GridLayoutDensity GridLayoutDensity = UIForia.Layout.GridLayoutDensity.Sparse;
		public static readonly IReadOnlyList<UIForia.Layout.LayoutTypes.GridTrackSize> GridLayoutColTemplate = ListPool<GridTrackSize>.Empty;
		public static readonly IReadOnlyList<UIForia.Layout.LayoutTypes.GridTrackSize> GridLayoutRowTemplate = ListPool<GridTrackSize>.Empty;
		public static readonly GridTrackSize GridLayoutColAutoSize = new GridTrackSize(1, GridTemplateUnit.MaxContent);
		public static readonly GridTrackSize GridLayoutRowAutoSize = new GridTrackSize(1, GridTemplateUnit.MaxContent);
		public const float GridLayoutColGap = 0;
		public const float GridLayoutRowGap = 0;
		public const CrossAxisAlignment GridLayoutColAlignment = UIForia.Layout.CrossAxisAlignment.Start;
		public const CrossAxisAlignment GridLayoutRowAlignment = UIForia.Layout.CrossAxisAlignment.Start;
		public static readonly UIMeasurement MinWidth = new UIMeasurement(0, UIMeasurementUnit.Pixel);
		public static readonly UIMeasurement MaxWidth = new UIMeasurement(3.402823E+38, UIMeasurementUnit.Pixel);
		public static readonly UIMeasurement PreferredWidth = new UIMeasurement(1, UIMeasurementUnit.Content);
		public static readonly UIMeasurement MinHeight = new UIMeasurement(0, UIMeasurementUnit.Pixel);
		public static readonly UIMeasurement MaxHeight = new UIMeasurement(3.402823E+38, UIMeasurementUnit.Pixel);
		public static readonly UIMeasurement PreferredHeight = new UIMeasurement(1, UIMeasurementUnit.Content);
		public static readonly UIMeasurement MarginTop = new UIMeasurement(0, UIMeasurementUnit.Pixel);
		public static readonly UIMeasurement MarginRight = new UIMeasurement(0, UIMeasurementUnit.Pixel);
		public static readonly UIMeasurement MarginBottom = new UIMeasurement(0, UIMeasurementUnit.Pixel);
		public static readonly UIMeasurement MarginLeft = new UIMeasurement(0, UIMeasurementUnit.Pixel);
		public static readonly UIFixedLength BorderTop = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength BorderRight = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength BorderBottom = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength BorderLeft = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength BorderRadiusTopLeft = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength BorderRadiusTopRight = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength BorderRadiusBottomRight = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength BorderRadiusBottomLeft = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength PaddingTop = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength PaddingRight = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength PaddingBottom = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength PaddingLeft = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly Color TextColor = new Color(0f, 0f, 0f, 1f);
		public static readonly TMP_FontAsset TextFontAsset = TMP_FontAsset.defaultFontAsset;
		public const int TextFontSize = 18;
		public const FontStyle TextFontStyle = UIForia.Text.FontStyle.Normal;
		public const TextAlignment TextAlignment = UIForia.Text.TextAlignment.Left;
		public const TextTransform TextTransform = UIForia.Text.TextTransform.None;
		public static readonly UIFixedLength AnchorTop = new UIFixedLength(0, UIFixedUnit.Percent);
		public static readonly UIFixedLength AnchorRight = new UIFixedLength(1, UIFixedUnit.Percent);
		public static readonly UIFixedLength AnchorBottom = new UIFixedLength(1, UIFixedUnit.Percent);
		public static readonly UIFixedLength AnchorLeft = new UIFixedLength(0, UIFixedUnit.Percent);
		public const AnchorTarget AnchorTarget = UIForia.Rendering.AnchorTarget.Parent;
		public static readonly UIFixedLength TransformPositionX = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength TransformPositionY = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength TransformPivotX = new UIFixedLength(0, UIFixedUnit.Pixel);
		public static readonly UIFixedLength TransformPivotY = new UIFixedLength(0, UIFixedUnit.Pixel);
		public const float TransformScaleX = 1;
		public const float TransformScaleY = 1;
		public const float TransformRotation = 0;
		public const TransformBehavior TransformBehaviorX = UIForia.Rendering.TransformBehavior.Default;
		public const TransformBehavior TransformBehaviorY = UIForia.Rendering.TransformBehavior.Default;
		public const LayoutType LayoutType = UIForia.Rendering.LayoutType.Flex;
		public const LayoutBehavior LayoutBehavior = UIForia.Layout.LayoutBehavior.Normal;
		public const int ZIndex = 0;
		public const int RenderLayerOffset = 0;
		public const RenderLayer RenderLayer = UIForia.Rendering.RenderLayer.Default;
		public const VerticalScrollbarAttachment ScrollbarVerticalAttachment = UIForia.Rendering.VerticalScrollbarAttachment.Right;
		public const ScrollbarButtonPlacement ScrollbarVerticalButtonPlacement = UIForia.Rendering.ScrollbarButtonPlacement.Hidden;
		public const float ScrollbarVerticalTrackSize = 10;
		public const float ScrollbarVerticalTrackBorderRadius = 0;
		public const float ScrollbarVerticalTrackBorderSize = 0;
		public static readonly Color ScrollbarVerticalTrackBorderColor = new Color(-1f, -1f, -1f, -1f);
		public static readonly Texture2D ScrollbarVerticalTrackImage = null;
		public static readonly Color ScrollbarVerticalTrackColor = new Color(0.5f, 0.5f, 0.5f, 1f);
		public const float ScrollbarVerticalHandleSize = 10;
		public const float ScrollbarVerticalHandleBorderRadius = 0;
		public const float ScrollbarVerticalHandleBorderSize = 0;
		public static readonly Color ScrollbarVerticalHandleBorderColor = new Color(-1f, -1f, -1f, -1f);
		public static readonly Texture2D ScrollbarVerticalHandleImage = null;
		public static readonly Color ScrollbarVerticalHandleColor = new Color(0.5f, 0.5f, 0.5f, 1f);
		public const float ScrollbarVerticalIncrementSize = 10;
		public const float ScrollbarVerticalIncrementBorderRadius = 0;
		public const float ScrollbarVerticalIncrementBorderSize = 0;
		public static readonly Color ScrollbarVerticalIncrementBorderColor = new Color(-1f, -1f, -1f, -1f);
		public static readonly Texture2D ScrollbarVerticalIncrementImage = null;
		public static readonly Color ScrollbarVerticalIncrementColor = new Color(0.5f, 0.5f, 0.5f, 1f);
		public const float ScrollbarVerticalDecrementSize = 10;
		public const float ScrollbarVerticalDecrementBorderRadius = 0;
		public const float ScrollbarVerticalDecrementBorderSize = 0;
		public static readonly Color ScrollbarVerticalDecrementBorderColor = new Color(-1f, -1f, -1f, -1f);
		public static readonly Texture2D ScrollbarVerticalDecrementImage = null;
		public static readonly Color ScrollbarVerticalDecrementColor = new Color(0.5f, 0.5f, 0.5f, 1f);
		public const HorizontalScrollbarAttachment ScrollbarHorizontalAttachment = UIForia.Rendering.HorizontalScrollbarAttachment.Bottom;
		public const ScrollbarButtonPlacement ScrollbarHorizontalButtonPlacement = UIForia.Rendering.ScrollbarButtonPlacement.Hidden;
		public const float ScrollbarHorizontalTrackSize = 10;
		public const float ScrollbarHorizontalTrackBorderRadius = 0;
		public const float ScrollbarHorizontalTrackBorderSize = 0;
		public static readonly Color ScrollbarHorizontalTrackBorderColor = new Color(-1f, -1f, -1f, -1f);
		public static readonly Texture2D ScrollbarHorizontalTrackImage = null;
		public static readonly Color ScrollbarHorizontalTrackColor = new Color(0.5f, 0.5f, 0.5f, 1f);
		public const float ScrollbarHorizontalHandleSize = 10;
		public const float ScrollbarHorizontalHandleBorderRadius = 0;
		public const float ScrollbarHorizontalHandleBorderSize = 0;
		public static readonly Color ScrollbarHorizontalHandleBorderColor = new Color(-1f, -1f, -1f, -1f);
		public static readonly Texture2D ScrollbarHorizontalHandleImage = null;
		public static readonly Color ScrollbarHorizontalHandleColor = new Color(0.5f, 0.5f, 0.5f, 1f);
		public const float ScrollbarHorizontalIncrementSize = 10;
		public const float ScrollbarHorizontalIncrementBorderRadius = 0;
		public const float ScrollbarHorizontalIncrementBorderSize = 0;
		public static readonly Color ScrollbarHorizontalIncrementBorderColor = new Color(-1f, -1f, -1f, -1f);
		public static readonly Texture2D ScrollbarHorizontalIncrementImage = null;
		public static readonly Color ScrollbarHorizontalIncrementColor = new Color(0.5f, 0.5f, 0.5f, 1f);
		public const float ScrollbarHorizontalDecrementSize = 10;
		public const float ScrollbarHorizontalDecrementBorderRadius = 0;
		public const float ScrollbarHorizontalDecrementBorderSize = 0;
		public static readonly Color ScrollbarHorizontalDecrementBorderColor = new Color(-1f, -1f, -1f, -1f);
		public static readonly Texture2D ScrollbarHorizontalDecrementImage = null;
		public static readonly Color ScrollbarHorizontalDecrementColor = new Color(0.5f, 0.5f, 0.5f, 1f);
		public static StyleProperty GetPropertyValue(StylePropertyId propertyId) {

			switch(propertyId) {
				case StylePropertyId.OverflowX:
					 return new StyleProperty(StylePropertyId.OverflowX, (int)UIForia.Rendering.Overflow.None);
				case StylePropertyId.OverflowY:
					 return new StyleProperty(StylePropertyId.OverflowY, (int)UIForia.Rendering.Overflow.None);
				case StylePropertyId.BorderColor:
					 return new StyleProperty(StylePropertyId.BorderColor, new Color(-1f, -1f, -1f, -1f));
				case StylePropertyId.BackgroundColor:
					 return new StyleProperty(StylePropertyId.BackgroundColor, new Color(-1f, -1f, -1f, -1f));
				case StylePropertyId.BackgroundColorSecondary:
					 return new StyleProperty(StylePropertyId.BackgroundColorSecondary, new Color(-1f, -1f, -1f, -1f));
				case StylePropertyId.BackgroundImage:
					 return new StyleProperty(StylePropertyId.BackgroundImage, 0, 0, null);
				case StylePropertyId.BackgroundImage1:
					 return new StyleProperty(StylePropertyId.BackgroundImage1, 0, 0, null);
				case StylePropertyId.BackgroundImage2:
					 return new StyleProperty(StylePropertyId.BackgroundImage2, 0, 0, null);
				case StylePropertyId.BackgroundGradientType:
					 return new StyleProperty(StylePropertyId.BackgroundGradientType, (int)Shapes2D.GradientType.Linear);
				case StylePropertyId.BackgroundGradientAxis:
					 return new StyleProperty(StylePropertyId.BackgroundGradientAxis, (int)Shapes2D.GradientAxis.Horizontal);
				case StylePropertyId.BackgroundGradientStart:
					 return new StyleProperty(StylePropertyId.BackgroundGradientStart, 0);
				case StylePropertyId.BackgroundFillRotation:
					 return new StyleProperty(StylePropertyId.BackgroundFillRotation, 0);
				case StylePropertyId.BackgroundFillType:
					 return new StyleProperty(StylePropertyId.BackgroundFillType, (int)UIForia.Rendering.BackgroundFillType.Normal);
				case StylePropertyId.BackgroundShapeType:
					 return new StyleProperty(StylePropertyId.BackgroundShapeType, (int)UIForia.Rendering.BackgroundShapeType.Rectangle);
				case StylePropertyId.BackgroundFillOffsetX:
					 return new StyleProperty(StylePropertyId.BackgroundFillOffsetX, 0);
				case StylePropertyId.BackgroundFillOffsetY:
					 return new StyleProperty(StylePropertyId.BackgroundFillOffsetY, 0);
				case StylePropertyId.BackgroundFillScaleX:
					 return new StyleProperty(StylePropertyId.BackgroundFillScaleX, 1);
				case StylePropertyId.BackgroundFillScaleY:
					 return new StyleProperty(StylePropertyId.BackgroundFillScaleY, 1);
				case StylePropertyId.Opacity:
					 return new StyleProperty(StylePropertyId.Opacity, 1);
				case StylePropertyId.Cursor:
					 return new StyleProperty(StylePropertyId.Cursor, 0, 0, null);
				case StylePropertyId.Visibility:
					 return new StyleProperty(StylePropertyId.Visibility, (int)UIForia.Rendering.Visibility.Visible);
				case StylePropertyId.FlexItemOrder:
					 return new StyleProperty(StylePropertyId.FlexItemOrder, 0);
				case StylePropertyId.FlexItemGrow:
					 return new StyleProperty(StylePropertyId.FlexItemGrow, 0);
				case StylePropertyId.FlexItemShrink:
					 return new StyleProperty(StylePropertyId.FlexItemShrink, 0);
				case StylePropertyId.FlexItemSelfAlignment:
					 return new StyleProperty(StylePropertyId.FlexItemSelfAlignment, (int)UIForia.Layout.CrossAxisAlignment.Unset);
				case StylePropertyId.FlexLayoutDirection:
					 return new StyleProperty(StylePropertyId.FlexLayoutDirection, (int)UIForia.Rendering.LayoutDirection.Row);
				case StylePropertyId.FlexLayoutWrap:
					 return new StyleProperty(StylePropertyId.FlexLayoutWrap, (int)UIForia.Rendering.LayoutWrap.None);
				case StylePropertyId.FlexLayoutMainAxisAlignment:
					 return new StyleProperty(StylePropertyId.FlexLayoutMainAxisAlignment, (int)UIForia.Layout.MainAxisAlignment.Start);
				case StylePropertyId.FlexLayoutCrossAxisAlignment:
					 return new StyleProperty(StylePropertyId.FlexLayoutCrossAxisAlignment, (int)UIForia.Layout.CrossAxisAlignment.Start);
				case StylePropertyId.GridItemColStart:
					 return new StyleProperty(StylePropertyId.GridItemColStart, 2147483647);
				case StylePropertyId.GridItemColSpan:
					 return new StyleProperty(StylePropertyId.GridItemColSpan, 1);
				case StylePropertyId.GridItemRowStart:
					 return new StyleProperty(StylePropertyId.GridItemRowStart, 2147483647);
				case StylePropertyId.GridItemRowSpan:
					 return new StyleProperty(StylePropertyId.GridItemRowSpan, 1);
				case StylePropertyId.GridItemColSelfAlignment:
					 return new StyleProperty(StylePropertyId.GridItemColSelfAlignment, (int)UIForia.Layout.CrossAxisAlignment.Unset);
				case StylePropertyId.GridItemRowSelfAlignment:
					 return new StyleProperty(StylePropertyId.GridItemRowSelfAlignment, (int)UIForia.Layout.CrossAxisAlignment.Unset);
				case StylePropertyId.GridLayoutDirection:
					 return new StyleProperty(StylePropertyId.GridLayoutDirection, (int)UIForia.Rendering.LayoutDirection.Row);
				case StylePropertyId.GridLayoutDensity:
					 return new StyleProperty(StylePropertyId.GridLayoutDensity, (int)UIForia.Layout.GridLayoutDensity.Sparse);
				case StylePropertyId.GridLayoutColTemplate:
					 return new StyleProperty(StylePropertyId.GridLayoutColTemplate, 0, 0, ListPool<GridTrackSize>.Empty);
				case StylePropertyId.GridLayoutRowTemplate:
					 return new StyleProperty(StylePropertyId.GridLayoutRowTemplate, 0, 0, ListPool<GridTrackSize>.Empty);
				case StylePropertyId.GridLayoutColAutoSize:
					 return new StyleProperty(StylePropertyId.GridLayoutColAutoSize, new GridTrackSize(1, GridTemplateUnit.MaxContent));
				case StylePropertyId.GridLayoutRowAutoSize:
					 return new StyleProperty(StylePropertyId.GridLayoutRowAutoSize, new GridTrackSize(1, GridTemplateUnit.MaxContent));
				case StylePropertyId.GridLayoutColGap:
					 return new StyleProperty(StylePropertyId.GridLayoutColGap, 0);
				case StylePropertyId.GridLayoutRowGap:
					 return new StyleProperty(StylePropertyId.GridLayoutRowGap, 0);
				case StylePropertyId.GridLayoutColAlignment:
					 return new StyleProperty(StylePropertyId.GridLayoutColAlignment, (int)UIForia.Layout.CrossAxisAlignment.Start);
				case StylePropertyId.GridLayoutRowAlignment:
					 return new StyleProperty(StylePropertyId.GridLayoutRowAlignment, (int)UIForia.Layout.CrossAxisAlignment.Start);
				case StylePropertyId.MinWidth:
					 return new StyleProperty(StylePropertyId.MinWidth, new UIMeasurement(0, UIMeasurementUnit.Pixel));
				case StylePropertyId.MaxWidth:
					 return new StyleProperty(StylePropertyId.MaxWidth, new UIMeasurement(3.402823E+38, UIMeasurementUnit.Pixel));
				case StylePropertyId.PreferredWidth:
					 return new StyleProperty(StylePropertyId.PreferredWidth, new UIMeasurement(1, UIMeasurementUnit.Content));
				case StylePropertyId.MinHeight:
					 return new StyleProperty(StylePropertyId.MinHeight, new UIMeasurement(0, UIMeasurementUnit.Pixel));
				case StylePropertyId.MaxHeight:
					 return new StyleProperty(StylePropertyId.MaxHeight, new UIMeasurement(3.402823E+38, UIMeasurementUnit.Pixel));
				case StylePropertyId.PreferredHeight:
					 return new StyleProperty(StylePropertyId.PreferredHeight, new UIMeasurement(1, UIMeasurementUnit.Content));
				case StylePropertyId.MarginTop:
					 return new StyleProperty(StylePropertyId.MarginTop, new UIMeasurement(0, UIMeasurementUnit.Pixel));
				case StylePropertyId.MarginRight:
					 return new StyleProperty(StylePropertyId.MarginRight, new UIMeasurement(0, UIMeasurementUnit.Pixel));
				case StylePropertyId.MarginBottom:
					 return new StyleProperty(StylePropertyId.MarginBottom, new UIMeasurement(0, UIMeasurementUnit.Pixel));
				case StylePropertyId.MarginLeft:
					 return new StyleProperty(StylePropertyId.MarginLeft, new UIMeasurement(0, UIMeasurementUnit.Pixel));
				case StylePropertyId.BorderTop:
					 return new StyleProperty(StylePropertyId.BorderTop, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.BorderRight:
					 return new StyleProperty(StylePropertyId.BorderRight, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.BorderBottom:
					 return new StyleProperty(StylePropertyId.BorderBottom, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.BorderLeft:
					 return new StyleProperty(StylePropertyId.BorderLeft, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.BorderRadiusTopLeft:
					 return new StyleProperty(StylePropertyId.BorderRadiusTopLeft, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.BorderRadiusTopRight:
					 return new StyleProperty(StylePropertyId.BorderRadiusTopRight, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.BorderRadiusBottomRight:
					 return new StyleProperty(StylePropertyId.BorderRadiusBottomRight, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.BorderRadiusBottomLeft:
					 return new StyleProperty(StylePropertyId.BorderRadiusBottomLeft, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.PaddingTop:
					 return new StyleProperty(StylePropertyId.PaddingTop, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.PaddingRight:
					 return new StyleProperty(StylePropertyId.PaddingRight, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.PaddingBottom:
					 return new StyleProperty(StylePropertyId.PaddingBottom, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.PaddingLeft:
					 return new StyleProperty(StylePropertyId.PaddingLeft, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.TextColor:
					 return new StyleProperty(StylePropertyId.TextColor, new Color(0f, 0f, 0f, 1f));
				case StylePropertyId.TextFontAsset:
					 return new StyleProperty(StylePropertyId.TextFontAsset, 0, 0, TMP_FontAsset.defaultFontAsset);
				case StylePropertyId.TextFontSize:
					 return new StyleProperty(StylePropertyId.TextFontSize, 18);
				case StylePropertyId.TextFontStyle:
					 return new StyleProperty(StylePropertyId.TextFontStyle, (int)UIForia.Text.FontStyle.Normal);
				case StylePropertyId.TextAlignment:
					 return new StyleProperty(StylePropertyId.TextAlignment, (int)UIForia.Text.TextAlignment.Left);
				case StylePropertyId.TextTransform:
					 return new StyleProperty(StylePropertyId.TextTransform, (int)UIForia.Text.TextTransform.None);
				case StylePropertyId.AnchorTop:
					 return new StyleProperty(StylePropertyId.AnchorTop, new UIFixedLength(0, UIFixedUnit.Percent));
				case StylePropertyId.AnchorRight:
					 return new StyleProperty(StylePropertyId.AnchorRight, new UIFixedLength(1, UIFixedUnit.Percent));
				case StylePropertyId.AnchorBottom:
					 return new StyleProperty(StylePropertyId.AnchorBottom, new UIFixedLength(1, UIFixedUnit.Percent));
				case StylePropertyId.AnchorLeft:
					 return new StyleProperty(StylePropertyId.AnchorLeft, new UIFixedLength(0, UIFixedUnit.Percent));
				case StylePropertyId.AnchorTarget:
					 return new StyleProperty(StylePropertyId.AnchorTarget, (int)UIForia.Rendering.AnchorTarget.Parent);
				case StylePropertyId.TransformPositionX:
					 return new StyleProperty(StylePropertyId.TransformPositionX, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.TransformPositionY:
					 return new StyleProperty(StylePropertyId.TransformPositionY, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.TransformPivotX:
					 return new StyleProperty(StylePropertyId.TransformPivotX, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.TransformPivotY:
					 return new StyleProperty(StylePropertyId.TransformPivotY, new UIFixedLength(0, UIFixedUnit.Pixel));
				case StylePropertyId.TransformScaleX:
					 return new StyleProperty(StylePropertyId.TransformScaleX, 1);
				case StylePropertyId.TransformScaleY:
					 return new StyleProperty(StylePropertyId.TransformScaleY, 1);
				case StylePropertyId.TransformRotation:
					 return new StyleProperty(StylePropertyId.TransformRotation, 0);
				case StylePropertyId.TransformBehaviorX:
					 return new StyleProperty(StylePropertyId.TransformBehaviorX, (int)UIForia.Rendering.TransformBehavior.Default);
				case StylePropertyId.TransformBehaviorY:
					 return new StyleProperty(StylePropertyId.TransformBehaviorY, (int)UIForia.Rendering.TransformBehavior.Default);
				case StylePropertyId.LayoutType:
					 return new StyleProperty(StylePropertyId.LayoutType, (int)UIForia.Rendering.LayoutType.Flex);
				case StylePropertyId.LayoutBehavior:
					 return new StyleProperty(StylePropertyId.LayoutBehavior, (int)UIForia.Layout.LayoutBehavior.Normal);
				case StylePropertyId.ZIndex:
					 return new StyleProperty(StylePropertyId.ZIndex, 0);
				case StylePropertyId.RenderLayerOffset:
					 return new StyleProperty(StylePropertyId.RenderLayerOffset, 0);
				case StylePropertyId.RenderLayer:
					 return new StyleProperty(StylePropertyId.RenderLayer, (int)UIForia.Rendering.RenderLayer.Default);
				case StylePropertyId.ScrollbarVerticalAttachment:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalAttachment, (int)UIForia.Rendering.VerticalScrollbarAttachment.Right);
				case StylePropertyId.ScrollbarVerticalButtonPlacement:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalButtonPlacement, (int)UIForia.Rendering.ScrollbarButtonPlacement.Hidden);
				case StylePropertyId.ScrollbarVerticalTrackSize:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalTrackSize, 10);
				case StylePropertyId.ScrollbarVerticalTrackBorderRadius:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalTrackBorderRadius, 0);
				case StylePropertyId.ScrollbarVerticalTrackBorderSize:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalTrackBorderSize, 0);
				case StylePropertyId.ScrollbarVerticalTrackBorderColor:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalTrackBorderColor, new Color(-1f, -1f, -1f, -1f));
				case StylePropertyId.ScrollbarVerticalTrackImage:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalTrackImage, 0, 0, null);
				case StylePropertyId.ScrollbarVerticalTrackColor:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalTrackColor, new Color(0.5f, 0.5f, 0.5f, 1f));
				case StylePropertyId.ScrollbarVerticalHandleSize:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalHandleSize, 10);
				case StylePropertyId.ScrollbarVerticalHandleBorderRadius:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalHandleBorderRadius, 0);
				case StylePropertyId.ScrollbarVerticalHandleBorderSize:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalHandleBorderSize, 0);
				case StylePropertyId.ScrollbarVerticalHandleBorderColor:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalHandleBorderColor, new Color(-1f, -1f, -1f, -1f));
				case StylePropertyId.ScrollbarVerticalHandleImage:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalHandleImage, 0, 0, null);
				case StylePropertyId.ScrollbarVerticalHandleColor:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalHandleColor, new Color(0.5f, 0.5f, 0.5f, 1f));
				case StylePropertyId.ScrollbarVerticalIncrementSize:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalIncrementSize, 10);
				case StylePropertyId.ScrollbarVerticalIncrementBorderRadius:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalIncrementBorderRadius, 0);
				case StylePropertyId.ScrollbarVerticalIncrementBorderSize:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalIncrementBorderSize, 0);
				case StylePropertyId.ScrollbarVerticalIncrementBorderColor:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalIncrementBorderColor, new Color(-1f, -1f, -1f, -1f));
				case StylePropertyId.ScrollbarVerticalIncrementImage:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalIncrementImage, 0, 0, null);
				case StylePropertyId.ScrollbarVerticalIncrementColor:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalIncrementColor, new Color(0.5f, 0.5f, 0.5f, 1f));
				case StylePropertyId.ScrollbarVerticalDecrementSize:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalDecrementSize, 10);
				case StylePropertyId.ScrollbarVerticalDecrementBorderRadius:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalDecrementBorderRadius, 0);
				case StylePropertyId.ScrollbarVerticalDecrementBorderSize:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalDecrementBorderSize, 0);
				case StylePropertyId.ScrollbarVerticalDecrementBorderColor:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalDecrementBorderColor, new Color(-1f, -1f, -1f, -1f));
				case StylePropertyId.ScrollbarVerticalDecrementImage:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalDecrementImage, 0, 0, null);
				case StylePropertyId.ScrollbarVerticalDecrementColor:
					 return new StyleProperty(StylePropertyId.ScrollbarVerticalDecrementColor, new Color(0.5f, 0.5f, 0.5f, 1f));
				case StylePropertyId.ScrollbarHorizontalAttachment:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalAttachment, (int)UIForia.Rendering.HorizontalScrollbarAttachment.Bottom);
				case StylePropertyId.ScrollbarHorizontalButtonPlacement:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalButtonPlacement, (int)UIForia.Rendering.ScrollbarButtonPlacement.Hidden);
				case StylePropertyId.ScrollbarHorizontalTrackSize:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalTrackSize, 10);
				case StylePropertyId.ScrollbarHorizontalTrackBorderRadius:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalTrackBorderRadius, 0);
				case StylePropertyId.ScrollbarHorizontalTrackBorderSize:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalTrackBorderSize, 0);
				case StylePropertyId.ScrollbarHorizontalTrackBorderColor:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalTrackBorderColor, new Color(-1f, -1f, -1f, -1f));
				case StylePropertyId.ScrollbarHorizontalTrackImage:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalTrackImage, 0, 0, null);
				case StylePropertyId.ScrollbarHorizontalTrackColor:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalTrackColor, new Color(0.5f, 0.5f, 0.5f, 1f));
				case StylePropertyId.ScrollbarHorizontalHandleSize:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalHandleSize, 10);
				case StylePropertyId.ScrollbarHorizontalHandleBorderRadius:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalHandleBorderRadius, 0);
				case StylePropertyId.ScrollbarHorizontalHandleBorderSize:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalHandleBorderSize, 0);
				case StylePropertyId.ScrollbarHorizontalHandleBorderColor:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalHandleBorderColor, new Color(-1f, -1f, -1f, -1f));
				case StylePropertyId.ScrollbarHorizontalHandleImage:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalHandleImage, 0, 0, null);
				case StylePropertyId.ScrollbarHorizontalHandleColor:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalHandleColor, new Color(0.5f, 0.5f, 0.5f, 1f));
				case StylePropertyId.ScrollbarHorizontalIncrementSize:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalIncrementSize, 10);
				case StylePropertyId.ScrollbarHorizontalIncrementBorderRadius:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalIncrementBorderRadius, 0);
				case StylePropertyId.ScrollbarHorizontalIncrementBorderSize:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalIncrementBorderSize, 0);
				case StylePropertyId.ScrollbarHorizontalIncrementBorderColor:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalIncrementBorderColor, new Color(-1f, -1f, -1f, -1f));
				case StylePropertyId.ScrollbarHorizontalIncrementImage:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalIncrementImage, 0, 0, null);
				case StylePropertyId.ScrollbarHorizontalIncrementColor:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalIncrementColor, new Color(0.5f, 0.5f, 0.5f, 1f));
				case StylePropertyId.ScrollbarHorizontalDecrementSize:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalDecrementSize, 10);
				case StylePropertyId.ScrollbarHorizontalDecrementBorderRadius:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalDecrementBorderRadius, 0);
				case StylePropertyId.ScrollbarHorizontalDecrementBorderSize:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalDecrementBorderSize, 0);
				case StylePropertyId.ScrollbarHorizontalDecrementBorderColor:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalDecrementBorderColor, new Color(-1f, -1f, -1f, -1f));
				case StylePropertyId.ScrollbarHorizontalDecrementImage:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalDecrementImage, 0, 0, null);
				case StylePropertyId.ScrollbarHorizontalDecrementColor:
					 return new StyleProperty(StylePropertyId.ScrollbarHorizontalDecrementColor, new Color(0.5f, 0.5f, 0.5f, 1f));
				default: throw new System.ArgumentOutOfRangeException(nameof(propertyId), propertyId, null);
				}
} 
}
}