using System;
using System.Diagnostics;
using Shapes2D;
using UIForia.Layout;
using UIForia.Layout.LayoutTypes;
using TMPro;
using System.Collections.Generic;
using UnityEngine;
using UIForia.Util;
using UIForia.Text;
using FontStyle = UIForia.Text.FontStyle;
using TextAlignment = UIForia.Text.TextAlignment;
// Do not edit this file. See CodeGen.cs instead.

namespace UIForia.Rendering {

    public partial class ComputedStyle {

		public Overflow OverflowX {
			[DebuggerStepThrough] get { return (Overflow)ReadIntProperty(StylePropertyId.OverflowX, (int)DefaultStyleValues_Generated.OverflowX); }
			internal set { WriteIntProperty(StylePropertyId.OverflowX, (int)value); } 
		}

		public Overflow OverflowY {
			[DebuggerStepThrough] get { return (Overflow)ReadIntProperty(StylePropertyId.OverflowY, (int)DefaultStyleValues_Generated.OverflowY); }
			internal set { WriteIntProperty(StylePropertyId.OverflowY, (int)value); } 
		}

		public Color BorderColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.BorderColor, DefaultStyleValues_Generated.BorderColor); }
			internal set { WriteColorProperty(StylePropertyId.BorderColor, value); } 
		}

		public Color BackgroundColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.BackgroundColor, DefaultStyleValues_Generated.BackgroundColor); }
			internal set { WriteColorProperty(StylePropertyId.BackgroundColor, value); } 
		}

		public Color BackgroundColorSecondary {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.BackgroundColorSecondary, DefaultStyleValues_Generated.BackgroundColorSecondary); }
			internal set { WriteColorProperty(StylePropertyId.BackgroundColorSecondary, value); } 
		}

		public Texture2D BackgroundImage {
			[DebuggerStepThrough] get { return (Texture2D)ReadObjectProperty(StylePropertyId.BackgroundImage, DefaultStyleValues_Generated.BackgroundImage); }
			internal set { WriteObjectProperty(StylePropertyId.BackgroundImage, value); } 
		}

		public Texture2D BackgroundImage1 {
			[DebuggerStepThrough] get { return (Texture2D)ReadObjectProperty(StylePropertyId.BackgroundImage1, DefaultStyleValues_Generated.BackgroundImage1); }
			internal set { WriteObjectProperty(StylePropertyId.BackgroundImage1, value); } 
		}

		public Texture2D BackgroundImage2 {
			[DebuggerStepThrough] get { return (Texture2D)ReadObjectProperty(StylePropertyId.BackgroundImage2, DefaultStyleValues_Generated.BackgroundImage2); }
			internal set { WriteObjectProperty(StylePropertyId.BackgroundImage2, value); } 
		}

		public GradientType BackgroundGradientType {
			[DebuggerStepThrough] get { return (GradientType)ReadIntProperty(StylePropertyId.BackgroundGradientType, (int)DefaultStyleValues_Generated.BackgroundGradientType); }
			internal set { WriteIntProperty(StylePropertyId.BackgroundGradientType, (int)value); } 
		}

		public GradientAxis BackgroundGradientAxis {
			[DebuggerStepThrough] get { return (GradientAxis)ReadIntProperty(StylePropertyId.BackgroundGradientAxis, (int)DefaultStyleValues_Generated.BackgroundGradientAxis); }
			internal set { WriteIntProperty(StylePropertyId.BackgroundGradientAxis, (int)value); } 
		}

		public float BackgroundGradientStart {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.BackgroundGradientStart, DefaultStyleValues_Generated.BackgroundGradientStart); }
			internal set { WriteFloatProperty(StylePropertyId.BackgroundGradientStart, value); } 
		}

		public float BackgroundFillRotation {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.BackgroundFillRotation, DefaultStyleValues_Generated.BackgroundFillRotation); }
			internal set { WriteFloatProperty(StylePropertyId.BackgroundFillRotation, value); } 
		}

		public BackgroundFillType BackgroundFillType {
			[DebuggerStepThrough] get { return (BackgroundFillType)ReadIntProperty(StylePropertyId.BackgroundFillType, (int)DefaultStyleValues_Generated.BackgroundFillType); }
			internal set { WriteIntProperty(StylePropertyId.BackgroundFillType, (int)value); } 
		}

		public BackgroundShapeType BackgroundShapeType {
			[DebuggerStepThrough] get { return (BackgroundShapeType)ReadIntProperty(StylePropertyId.BackgroundShapeType, (int)DefaultStyleValues_Generated.BackgroundShapeType); }
			internal set { WriteIntProperty(StylePropertyId.BackgroundShapeType, (int)value); } 
		}

		public float BackgroundFillOffsetX {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.BackgroundFillOffsetX, DefaultStyleValues_Generated.BackgroundFillOffsetX); }
			internal set { WriteFloatProperty(StylePropertyId.BackgroundFillOffsetX, value); } 
		}

		public float BackgroundFillOffsetY {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.BackgroundFillOffsetY, DefaultStyleValues_Generated.BackgroundFillOffsetY); }
			internal set { WriteFloatProperty(StylePropertyId.BackgroundFillOffsetY, value); } 
		}

		public float BackgroundFillScaleX {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.BackgroundFillScaleX, DefaultStyleValues_Generated.BackgroundFillScaleX); }
			internal set { WriteFloatProperty(StylePropertyId.BackgroundFillScaleX, value); } 
		}

		public float BackgroundFillScaleY {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.BackgroundFillScaleY, DefaultStyleValues_Generated.BackgroundFillScaleY); }
			internal set { WriteFloatProperty(StylePropertyId.BackgroundFillScaleY, value); } 
		}

		public int FlexItemOrder {
			[DebuggerStepThrough] get { return ReadIntProperty(StylePropertyId.FlexItemOrder, DefaultStyleValues_Generated.FlexItemOrder); }
			internal set { WriteIntProperty(StylePropertyId.FlexItemOrder, value); } 
		}

		public int FlexItemGrow {
			[DebuggerStepThrough] get { return ReadIntProperty(StylePropertyId.FlexItemGrow, DefaultStyleValues_Generated.FlexItemGrow); }
			internal set { WriteIntProperty(StylePropertyId.FlexItemGrow, value); } 
		}

		public int FlexItemShrink {
			[DebuggerStepThrough] get { return ReadIntProperty(StylePropertyId.FlexItemShrink, DefaultStyleValues_Generated.FlexItemShrink); }
			internal set { WriteIntProperty(StylePropertyId.FlexItemShrink, value); } 
		}

		public CrossAxisAlignment FlexItemSelfAlignment {
			[DebuggerStepThrough] get { return (CrossAxisAlignment)ReadIntProperty(StylePropertyId.FlexItemSelfAlignment, (int)DefaultStyleValues_Generated.FlexItemSelfAlignment); }
			internal set { WriteIntProperty(StylePropertyId.FlexItemSelfAlignment, (int)value); } 
		}

		public LayoutDirection FlexLayoutDirection {
			[DebuggerStepThrough] get { return (LayoutDirection)ReadIntProperty(StylePropertyId.FlexLayoutDirection, (int)DefaultStyleValues_Generated.FlexLayoutDirection); }
			internal set { WriteIntProperty(StylePropertyId.FlexLayoutDirection, (int)value); } 
		}

		public LayoutWrap FlexLayoutWrap {
			[DebuggerStepThrough] get { return (LayoutWrap)ReadIntProperty(StylePropertyId.FlexLayoutWrap, (int)DefaultStyleValues_Generated.FlexLayoutWrap); }
			internal set { WriteIntProperty(StylePropertyId.FlexLayoutWrap, (int)value); } 
		}

		public MainAxisAlignment FlexLayoutMainAxisAlignment {
			[DebuggerStepThrough] get { return (MainAxisAlignment)ReadIntProperty(StylePropertyId.FlexLayoutMainAxisAlignment, (int)DefaultStyleValues_Generated.FlexLayoutMainAxisAlignment); }
			internal set { WriteIntProperty(StylePropertyId.FlexLayoutMainAxisAlignment, (int)value); } 
		}

		public CrossAxisAlignment FlexLayoutCrossAxisAlignment {
			[DebuggerStepThrough] get { return (CrossAxisAlignment)ReadIntProperty(StylePropertyId.FlexLayoutCrossAxisAlignment, (int)DefaultStyleValues_Generated.FlexLayoutCrossAxisAlignment); }
			internal set { WriteIntProperty(StylePropertyId.FlexLayoutCrossAxisAlignment, (int)value); } 
		}

		public int GridItemColStart {
			[DebuggerStepThrough] get { return ReadIntProperty(StylePropertyId.GridItemColStart, DefaultStyleValues_Generated.GridItemColStart); }
			internal set { WriteIntProperty(StylePropertyId.GridItemColStart, value); } 
		}

		public int GridItemColSpan {
			[DebuggerStepThrough] get { return ReadIntProperty(StylePropertyId.GridItemColSpan, DefaultStyleValues_Generated.GridItemColSpan); }
			internal set { WriteIntProperty(StylePropertyId.GridItemColSpan, value); } 
		}

		public int GridItemRowStart {
			[DebuggerStepThrough] get { return ReadIntProperty(StylePropertyId.GridItemRowStart, DefaultStyleValues_Generated.GridItemRowStart); }
			internal set { WriteIntProperty(StylePropertyId.GridItemRowStart, value); } 
		}

		public int GridItemRowSpan {
			[DebuggerStepThrough] get { return ReadIntProperty(StylePropertyId.GridItemRowSpan, DefaultStyleValues_Generated.GridItemRowSpan); }
			internal set { WriteIntProperty(StylePropertyId.GridItemRowSpan, value); } 
		}

		public CrossAxisAlignment GridItemColSelfAlignment {
			[DebuggerStepThrough] get { return (CrossAxisAlignment)ReadIntProperty(StylePropertyId.GridItemColSelfAlignment, (int)DefaultStyleValues_Generated.GridItemColSelfAlignment); }
			internal set { WriteIntProperty(StylePropertyId.GridItemColSelfAlignment, (int)value); } 
		}

		public CrossAxisAlignment GridItemRowSelfAlignment {
			[DebuggerStepThrough] get { return (CrossAxisAlignment)ReadIntProperty(StylePropertyId.GridItemRowSelfAlignment, (int)DefaultStyleValues_Generated.GridItemRowSelfAlignment); }
			internal set { WriteIntProperty(StylePropertyId.GridItemRowSelfAlignment, (int)value); } 
		}

		public LayoutDirection GridLayoutDirection {
			[DebuggerStepThrough] get { return (LayoutDirection)ReadIntProperty(StylePropertyId.GridLayoutDirection, (int)DefaultStyleValues_Generated.GridLayoutDirection); }
			internal set { WriteIntProperty(StylePropertyId.GridLayoutDirection, (int)value); } 
		}

		public GridLayoutDensity GridLayoutDensity {
			[DebuggerStepThrough] get { return (GridLayoutDensity)ReadIntProperty(StylePropertyId.GridLayoutDensity, (int)DefaultStyleValues_Generated.GridLayoutDensity); }
			internal set { WriteIntProperty(StylePropertyId.GridLayoutDensity, (int)value); } 
		}

		public IReadOnlyList<GridTrackSize> GridLayoutColTemplate {
			[DebuggerStepThrough] get { return (IReadOnlyList<GridTrackSize>)ReadObjectProperty(StylePropertyId.GridLayoutColTemplate, DefaultStyleValues_Generated.GridLayoutColTemplate); }
			internal set { WriteObjectProperty(StylePropertyId.GridLayoutColTemplate, value); } 
		}

		public IReadOnlyList<GridTrackSize> GridLayoutRowTemplate {
			[DebuggerStepThrough] get { return (IReadOnlyList<GridTrackSize>)ReadObjectProperty(StylePropertyId.GridLayoutRowTemplate, DefaultStyleValues_Generated.GridLayoutRowTemplate); }
			internal set { WriteObjectProperty(StylePropertyId.GridLayoutRowTemplate, value); } 
		}

		public GridTrackSize GridLayoutColAutoSize {
			[DebuggerStepThrough] get { return ReadGridTrackSizeProperty(StylePropertyId.GridLayoutColAutoSize, DefaultStyleValues_Generated.GridLayoutColAutoSize); }
			internal set { WriteGridTrackSizeProperty(StylePropertyId.GridLayoutColAutoSize, value); } 
		}

		public GridTrackSize GridLayoutRowAutoSize {
			[DebuggerStepThrough] get { return ReadGridTrackSizeProperty(StylePropertyId.GridLayoutRowAutoSize, DefaultStyleValues_Generated.GridLayoutRowAutoSize); }
			internal set { WriteGridTrackSizeProperty(StylePropertyId.GridLayoutRowAutoSize, value); } 
		}

		public float GridLayoutColGap {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.GridLayoutColGap, DefaultStyleValues_Generated.GridLayoutColGap); }
			internal set { WriteFloatProperty(StylePropertyId.GridLayoutColGap, value); } 
		}

		public float GridLayoutRowGap {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.GridLayoutRowGap, DefaultStyleValues_Generated.GridLayoutRowGap); }
			internal set { WriteFloatProperty(StylePropertyId.GridLayoutRowGap, value); } 
		}

		public CrossAxisAlignment GridLayoutColAlignment {
			[DebuggerStepThrough] get { return (CrossAxisAlignment)ReadIntProperty(StylePropertyId.GridLayoutColAlignment, (int)DefaultStyleValues_Generated.GridLayoutColAlignment); }
			internal set { WriteIntProperty(StylePropertyId.GridLayoutColAlignment, (int)value); } 
		}

		public CrossAxisAlignment GridLayoutRowAlignment {
			[DebuggerStepThrough] get { return (CrossAxisAlignment)ReadIntProperty(StylePropertyId.GridLayoutRowAlignment, (int)DefaultStyleValues_Generated.GridLayoutRowAlignment); }
			internal set { WriteIntProperty(StylePropertyId.GridLayoutRowAlignment, (int)value); } 
		}

		public UIMeasurement MinWidth {
			[DebuggerStepThrough] get { return ReadMeasurementProperty(StylePropertyId.MinWidth, DefaultStyleValues_Generated.MinWidth); }
			internal set { WriteMeasurementProperty(StylePropertyId.MinWidth, value); } 
		}

		public UIMeasurement MaxWidth {
			[DebuggerStepThrough] get { return ReadMeasurementProperty(StylePropertyId.MaxWidth, DefaultStyleValues_Generated.MaxWidth); }
			internal set { WriteMeasurementProperty(StylePropertyId.MaxWidth, value); } 
		}

		public UIMeasurement PreferredWidth {
			[DebuggerStepThrough] get { return ReadMeasurementProperty(StylePropertyId.PreferredWidth, DefaultStyleValues_Generated.PreferredWidth); }
			internal set { WriteMeasurementProperty(StylePropertyId.PreferredWidth, value); } 
		}

		public UIMeasurement MinHeight {
			[DebuggerStepThrough] get { return ReadMeasurementProperty(StylePropertyId.MinHeight, DefaultStyleValues_Generated.MinHeight); }
			internal set { WriteMeasurementProperty(StylePropertyId.MinHeight, value); } 
		}

		public UIMeasurement MaxHeight {
			[DebuggerStepThrough] get { return ReadMeasurementProperty(StylePropertyId.MaxHeight, DefaultStyleValues_Generated.MaxHeight); }
			internal set { WriteMeasurementProperty(StylePropertyId.MaxHeight, value); } 
		}

		public UIMeasurement PreferredHeight {
			[DebuggerStepThrough] get { return ReadMeasurementProperty(StylePropertyId.PreferredHeight, DefaultStyleValues_Generated.PreferredHeight); }
			internal set { WriteMeasurementProperty(StylePropertyId.PreferredHeight, value); } 
		}

		public UIMeasurement MarginTop {
			[DebuggerStepThrough] get { return ReadMeasurementProperty(StylePropertyId.MarginTop, DefaultStyleValues_Generated.MarginTop); }
			internal set { WriteMeasurementProperty(StylePropertyId.MarginTop, value); } 
		}

		public UIMeasurement MarginRight {
			[DebuggerStepThrough] get { return ReadMeasurementProperty(StylePropertyId.MarginRight, DefaultStyleValues_Generated.MarginRight); }
			internal set { WriteMeasurementProperty(StylePropertyId.MarginRight, value); } 
		}

		public UIMeasurement MarginBottom {
			[DebuggerStepThrough] get { return ReadMeasurementProperty(StylePropertyId.MarginBottom, DefaultStyleValues_Generated.MarginBottom); }
			internal set { WriteMeasurementProperty(StylePropertyId.MarginBottom, value); } 
		}

		public UIMeasurement MarginLeft {
			[DebuggerStepThrough] get { return ReadMeasurementProperty(StylePropertyId.MarginLeft, DefaultStyleValues_Generated.MarginLeft); }
			internal set { WriteMeasurementProperty(StylePropertyId.MarginLeft, value); } 
		}

		public UIFixedLength BorderTop {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.BorderTop, DefaultStyleValues_Generated.BorderTop); }
			internal set { WriteFixedLengthProperty(StylePropertyId.BorderTop, value); } 
		}

		public UIFixedLength BorderRight {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.BorderRight, DefaultStyleValues_Generated.BorderRight); }
			internal set { WriteFixedLengthProperty(StylePropertyId.BorderRight, value); } 
		}

		public UIFixedLength BorderBottom {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.BorderBottom, DefaultStyleValues_Generated.BorderBottom); }
			internal set { WriteFixedLengthProperty(StylePropertyId.BorderBottom, value); } 
		}

		public UIFixedLength BorderLeft {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.BorderLeft, DefaultStyleValues_Generated.BorderLeft); }
			internal set { WriteFixedLengthProperty(StylePropertyId.BorderLeft, value); } 
		}

		public UIFixedLength BorderRadiusTopLeft {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.BorderRadiusTopLeft, DefaultStyleValues_Generated.BorderRadiusTopLeft); }
			internal set { WriteFixedLengthProperty(StylePropertyId.BorderRadiusTopLeft, value); } 
		}

		public UIFixedLength BorderRadiusTopRight {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.BorderRadiusTopRight, DefaultStyleValues_Generated.BorderRadiusTopRight); }
			internal set { WriteFixedLengthProperty(StylePropertyId.BorderRadiusTopRight, value); } 
		}

		public UIFixedLength BorderRadiusBottomRight {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.BorderRadiusBottomRight, DefaultStyleValues_Generated.BorderRadiusBottomRight); }
			internal set { WriteFixedLengthProperty(StylePropertyId.BorderRadiusBottomRight, value); } 
		}

		public UIFixedLength BorderRadiusBottomLeft {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.BorderRadiusBottomLeft, DefaultStyleValues_Generated.BorderRadiusBottomLeft); }
			internal set { WriteFixedLengthProperty(StylePropertyId.BorderRadiusBottomLeft, value); } 
		}

		public UIFixedLength PaddingTop {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.PaddingTop, DefaultStyleValues_Generated.PaddingTop); }
			internal set { WriteFixedLengthProperty(StylePropertyId.PaddingTop, value); } 
		}

		public UIFixedLength PaddingRight {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.PaddingRight, DefaultStyleValues_Generated.PaddingRight); }
			internal set { WriteFixedLengthProperty(StylePropertyId.PaddingRight, value); } 
		}

		public UIFixedLength PaddingBottom {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.PaddingBottom, DefaultStyleValues_Generated.PaddingBottom); }
			internal set { WriteFixedLengthProperty(StylePropertyId.PaddingBottom, value); } 
		}

		public UIFixedLength PaddingLeft {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.PaddingLeft, DefaultStyleValues_Generated.PaddingLeft); }
			internal set { WriteFixedLengthProperty(StylePropertyId.PaddingLeft, value); } 
		}

		public Color TextColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.TextColor, DefaultStyleValues_Generated.TextColor); }
			internal set { WriteColorProperty(StylePropertyId.TextColor, value); } 
		}

		public TMP_FontAsset TextFontAsset {
			[DebuggerStepThrough] get { return (TMP_FontAsset)ReadObjectProperty(StylePropertyId.TextFontAsset, DefaultStyleValues_Generated.TextFontAsset); }
			internal set { WriteObjectProperty(StylePropertyId.TextFontAsset, value); } 
		}

		public int TextFontSize {
			[DebuggerStepThrough] get { return ReadIntProperty(StylePropertyId.TextFontSize, DefaultStyleValues_Generated.TextFontSize); }
			internal set { WriteIntProperty(StylePropertyId.TextFontSize, value); } 
		}

		public FontStyle TextFontStyle {
			[DebuggerStepThrough] get { return (FontStyle)ReadIntProperty(StylePropertyId.TextFontStyle, (int)DefaultStyleValues_Generated.TextFontStyle); }
			internal set { WriteIntProperty(StylePropertyId.TextFontStyle, (int)value); } 
		}

		public TextAlignment TextAlignment {
			[DebuggerStepThrough] get { return (TextAlignment)ReadIntProperty(StylePropertyId.TextAlignment, (int)DefaultStyleValues_Generated.TextAlignment); }
			internal set { WriteIntProperty(StylePropertyId.TextAlignment, (int)value); } 
		}

		public TextTransform TextTransform {
			[DebuggerStepThrough] get { return (TextTransform)ReadIntProperty(StylePropertyId.TextTransform, (int)DefaultStyleValues_Generated.TextTransform); }
			internal set { WriteIntProperty(StylePropertyId.TextTransform, (int)value); } 
		}

		public UIFixedLength AnchorTop {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.AnchorTop, DefaultStyleValues_Generated.AnchorTop); }
			internal set { WriteFixedLengthProperty(StylePropertyId.AnchorTop, value); } 
		}

		public UIFixedLength AnchorRight {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.AnchorRight, DefaultStyleValues_Generated.AnchorRight); }
			internal set { WriteFixedLengthProperty(StylePropertyId.AnchorRight, value); } 
		}

		public UIFixedLength AnchorBottom {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.AnchorBottom, DefaultStyleValues_Generated.AnchorBottom); }
			internal set { WriteFixedLengthProperty(StylePropertyId.AnchorBottom, value); } 
		}

		public UIFixedLength AnchorLeft {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.AnchorLeft, DefaultStyleValues_Generated.AnchorLeft); }
			internal set { WriteFixedLengthProperty(StylePropertyId.AnchorLeft, value); } 
		}

		public AnchorTarget AnchorTarget {
			[DebuggerStepThrough] get { return (AnchorTarget)ReadIntProperty(StylePropertyId.AnchorTarget, (int)DefaultStyleValues_Generated.AnchorTarget); }
			internal set { WriteIntProperty(StylePropertyId.AnchorTarget, (int)value); } 
		}

		public UIFixedLength TransformPositionX {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.TransformPositionX, DefaultStyleValues_Generated.TransformPositionX); }
			internal set { WriteFixedLengthProperty(StylePropertyId.TransformPositionX, value); } 
		}

		public UIFixedLength TransformPositionY {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.TransformPositionY, DefaultStyleValues_Generated.TransformPositionY); }
			internal set { WriteFixedLengthProperty(StylePropertyId.TransformPositionY, value); } 
		}

		public UIFixedLength TransformPivotX {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.TransformPivotX, DefaultStyleValues_Generated.TransformPivotX); }
			internal set { WriteFixedLengthProperty(StylePropertyId.TransformPivotX, value); } 
		}

		public UIFixedLength TransformPivotY {
			[DebuggerStepThrough] get { return ReadFixedLengthProperty(StylePropertyId.TransformPivotY, DefaultStyleValues_Generated.TransformPivotY); }
			internal set { WriteFixedLengthProperty(StylePropertyId.TransformPivotY, value); } 
		}

		public float TransformScaleX {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.TransformScaleX, DefaultStyleValues_Generated.TransformScaleX); }
			internal set { WriteFloatProperty(StylePropertyId.TransformScaleX, value); } 
		}

		public float TransformScaleY {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.TransformScaleY, DefaultStyleValues_Generated.TransformScaleY); }
			internal set { WriteFloatProperty(StylePropertyId.TransformScaleY, value); } 
		}

		public float TransformRotation {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.TransformRotation, DefaultStyleValues_Generated.TransformRotation); }
			internal set { WriteFloatProperty(StylePropertyId.TransformRotation, value); } 
		}

		public TransformBehavior TransformBehaviorX {
			[DebuggerStepThrough] get { return (TransformBehavior)ReadIntProperty(StylePropertyId.TransformBehaviorX, (int)DefaultStyleValues_Generated.TransformBehaviorX); }
			internal set { WriteIntProperty(StylePropertyId.TransformBehaviorX, (int)value); } 
		}

		public TransformBehavior TransformBehaviorY {
			[DebuggerStepThrough] get { return (TransformBehavior)ReadIntProperty(StylePropertyId.TransformBehaviorY, (int)DefaultStyleValues_Generated.TransformBehaviorY); }
			internal set { WriteIntProperty(StylePropertyId.TransformBehaviorY, (int)value); } 
		}

		public LayoutType LayoutType {
			[DebuggerStepThrough] get { return (LayoutType)ReadIntProperty(StylePropertyId.LayoutType, (int)DefaultStyleValues_Generated.LayoutType); }
			internal set { WriteIntProperty(StylePropertyId.LayoutType, (int)value); } 
		}

		public LayoutBehavior LayoutBehavior {
			[DebuggerStepThrough] get { return (LayoutBehavior)ReadIntProperty(StylePropertyId.LayoutBehavior, (int)DefaultStyleValues_Generated.LayoutBehavior); }
			internal set { WriteIntProperty(StylePropertyId.LayoutBehavior, (int)value); } 
		}

		public int ZIndex {
			[DebuggerStepThrough] get { return ReadIntProperty(StylePropertyId.ZIndex, DefaultStyleValues_Generated.ZIndex); }
			internal set { WriteIntProperty(StylePropertyId.ZIndex, value); } 
		}

		public int RenderLayerOffset {
			[DebuggerStepThrough] get { return ReadIntProperty(StylePropertyId.RenderLayerOffset, DefaultStyleValues_Generated.RenderLayerOffset); }
			internal set { WriteIntProperty(StylePropertyId.RenderLayerOffset, value); } 
		}

		public RenderLayer RenderLayer {
			[DebuggerStepThrough] get { return (RenderLayer)ReadIntProperty(StylePropertyId.RenderLayer, (int)DefaultStyleValues_Generated.RenderLayer); }
			internal set { WriteIntProperty(StylePropertyId.RenderLayer, (int)value); } 
		}

		public VerticalScrollbarAttachment ScrollbarVerticalAttachment {
			[DebuggerStepThrough] get { return (VerticalScrollbarAttachment)ReadIntProperty(StylePropertyId.ScrollbarVerticalAttachment, (int)DefaultStyleValues_Generated.ScrollbarVerticalAttachment); }
			internal set { WriteIntProperty(StylePropertyId.ScrollbarVerticalAttachment, (int)value); } 
		}

		public ScrollbarButtonPlacement ScrollbarVerticalButtonPlacement {
			[DebuggerStepThrough] get { return (ScrollbarButtonPlacement)ReadIntProperty(StylePropertyId.ScrollbarVerticalButtonPlacement, (int)DefaultStyleValues_Generated.ScrollbarVerticalButtonPlacement); }
			internal set { WriteIntProperty(StylePropertyId.ScrollbarVerticalButtonPlacement, (int)value); } 
		}

		public float ScrollbarVerticalTrackSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalTrackSize, DefaultStyleValues_Generated.ScrollbarVerticalTrackSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalTrackSize, value); } 
		}

		public float ScrollbarVerticalTrackBorderRadius {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalTrackBorderRadius, DefaultStyleValues_Generated.ScrollbarVerticalTrackBorderRadius); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalTrackBorderRadius, value); } 
		}

		public float ScrollbarVerticalTrackBorderSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalTrackBorderSize, DefaultStyleValues_Generated.ScrollbarVerticalTrackBorderSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalTrackBorderSize, value); } 
		}

		public Color ScrollbarVerticalTrackBorderColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarVerticalTrackBorderColor, DefaultStyleValues_Generated.ScrollbarVerticalTrackBorderColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarVerticalTrackBorderColor, value); } 
		}

		public Texture2D ScrollbarVerticalTrackImage {
			[DebuggerStepThrough] get { return (Texture2D)ReadObjectProperty(StylePropertyId.ScrollbarVerticalTrackImage, DefaultStyleValues_Generated.ScrollbarVerticalTrackImage); }
			internal set { WriteObjectProperty(StylePropertyId.ScrollbarVerticalTrackImage, value); } 
		}

		public Color ScrollbarVerticalTrackColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarVerticalTrackColor, DefaultStyleValues_Generated.ScrollbarVerticalTrackColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarVerticalTrackColor, value); } 
		}

		public float ScrollbarVerticalHandleSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalHandleSize, DefaultStyleValues_Generated.ScrollbarVerticalHandleSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalHandleSize, value); } 
		}

		public float ScrollbarVerticalHandleBorderRadius {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalHandleBorderRadius, DefaultStyleValues_Generated.ScrollbarVerticalHandleBorderRadius); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalHandleBorderRadius, value); } 
		}

		public float ScrollbarVerticalHandleBorderSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalHandleBorderSize, DefaultStyleValues_Generated.ScrollbarVerticalHandleBorderSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalHandleBorderSize, value); } 
		}

		public Color ScrollbarVerticalHandleBorderColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarVerticalHandleBorderColor, DefaultStyleValues_Generated.ScrollbarVerticalHandleBorderColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarVerticalHandleBorderColor, value); } 
		}

		public Texture2D ScrollbarVerticalHandleImage {
			[DebuggerStepThrough] get { return (Texture2D)ReadObjectProperty(StylePropertyId.ScrollbarVerticalHandleImage, DefaultStyleValues_Generated.ScrollbarVerticalHandleImage); }
			internal set { WriteObjectProperty(StylePropertyId.ScrollbarVerticalHandleImage, value); } 
		}

		public Color ScrollbarVerticalHandleColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarVerticalHandleColor, DefaultStyleValues_Generated.ScrollbarVerticalHandleColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarVerticalHandleColor, value); } 
		}

		public float ScrollbarVerticalIncrementSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalIncrementSize, DefaultStyleValues_Generated.ScrollbarVerticalIncrementSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalIncrementSize, value); } 
		}

		public float ScrollbarVerticalIncrementBorderRadius {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalIncrementBorderRadius, DefaultStyleValues_Generated.ScrollbarVerticalIncrementBorderRadius); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalIncrementBorderRadius, value); } 
		}

		public float ScrollbarVerticalIncrementBorderSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalIncrementBorderSize, DefaultStyleValues_Generated.ScrollbarVerticalIncrementBorderSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalIncrementBorderSize, value); } 
		}

		public Color ScrollbarVerticalIncrementBorderColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarVerticalIncrementBorderColor, DefaultStyleValues_Generated.ScrollbarVerticalIncrementBorderColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarVerticalIncrementBorderColor, value); } 
		}

		public Texture2D ScrollbarVerticalIncrementImage {
			[DebuggerStepThrough] get { return (Texture2D)ReadObjectProperty(StylePropertyId.ScrollbarVerticalIncrementImage, DefaultStyleValues_Generated.ScrollbarVerticalIncrementImage); }
			internal set { WriteObjectProperty(StylePropertyId.ScrollbarVerticalIncrementImage, value); } 
		}

		public Color ScrollbarVerticalIncrementColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarVerticalIncrementColor, DefaultStyleValues_Generated.ScrollbarVerticalIncrementColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarVerticalIncrementColor, value); } 
		}

		public float ScrollbarVerticalDecrementSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalDecrementSize, DefaultStyleValues_Generated.ScrollbarVerticalDecrementSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalDecrementSize, value); } 
		}

		public float ScrollbarVerticalDecrementBorderRadius {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalDecrementBorderRadius, DefaultStyleValues_Generated.ScrollbarVerticalDecrementBorderRadius); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalDecrementBorderRadius, value); } 
		}

		public float ScrollbarVerticalDecrementBorderSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarVerticalDecrementBorderSize, DefaultStyleValues_Generated.ScrollbarVerticalDecrementBorderSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarVerticalDecrementBorderSize, value); } 
		}

		public Color ScrollbarVerticalDecrementBorderColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarVerticalDecrementBorderColor, DefaultStyleValues_Generated.ScrollbarVerticalDecrementBorderColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarVerticalDecrementBorderColor, value); } 
		}

		public Texture2D ScrollbarVerticalDecrementImage {
			[DebuggerStepThrough] get { return (Texture2D)ReadObjectProperty(StylePropertyId.ScrollbarVerticalDecrementImage, DefaultStyleValues_Generated.ScrollbarVerticalDecrementImage); }
			internal set { WriteObjectProperty(StylePropertyId.ScrollbarVerticalDecrementImage, value); } 
		}

		public Color ScrollbarVerticalDecrementColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarVerticalDecrementColor, DefaultStyleValues_Generated.ScrollbarVerticalDecrementColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarVerticalDecrementColor, value); } 
		}

		public HorizontalScrollbarAttachment ScrollbarHorizontalAttachment {
			[DebuggerStepThrough] get { return (HorizontalScrollbarAttachment)ReadIntProperty(StylePropertyId.ScrollbarHorizontalAttachment, (int)DefaultStyleValues_Generated.ScrollbarHorizontalAttachment); }
			internal set { WriteIntProperty(StylePropertyId.ScrollbarHorizontalAttachment, (int)value); } 
		}

		public ScrollbarButtonPlacement ScrollbarHorizontalButtonPlacement {
			[DebuggerStepThrough] get { return (ScrollbarButtonPlacement)ReadIntProperty(StylePropertyId.ScrollbarHorizontalButtonPlacement, (int)DefaultStyleValues_Generated.ScrollbarHorizontalButtonPlacement); }
			internal set { WriteIntProperty(StylePropertyId.ScrollbarHorizontalButtonPlacement, (int)value); } 
		}

		public float ScrollbarHorizontalTrackSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalTrackSize, DefaultStyleValues_Generated.ScrollbarHorizontalTrackSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalTrackSize, value); } 
		}

		public float ScrollbarHorizontalTrackBorderRadius {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalTrackBorderRadius, DefaultStyleValues_Generated.ScrollbarHorizontalTrackBorderRadius); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalTrackBorderRadius, value); } 
		}

		public float ScrollbarHorizontalTrackBorderSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalTrackBorderSize, DefaultStyleValues_Generated.ScrollbarHorizontalTrackBorderSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalTrackBorderSize, value); } 
		}

		public Color ScrollbarHorizontalTrackBorderColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarHorizontalTrackBorderColor, DefaultStyleValues_Generated.ScrollbarHorizontalTrackBorderColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarHorizontalTrackBorderColor, value); } 
		}

		public Texture2D ScrollbarHorizontalTrackImage {
			[DebuggerStepThrough] get { return (Texture2D)ReadObjectProperty(StylePropertyId.ScrollbarHorizontalTrackImage, DefaultStyleValues_Generated.ScrollbarHorizontalTrackImage); }
			internal set { WriteObjectProperty(StylePropertyId.ScrollbarHorizontalTrackImage, value); } 
		}

		public Color ScrollbarHorizontalTrackColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarHorizontalTrackColor, DefaultStyleValues_Generated.ScrollbarHorizontalTrackColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarHorizontalTrackColor, value); } 
		}

		public float ScrollbarHorizontalHandleSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalHandleSize, DefaultStyleValues_Generated.ScrollbarHorizontalHandleSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalHandleSize, value); } 
		}

		public float ScrollbarHorizontalHandleBorderRadius {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalHandleBorderRadius, DefaultStyleValues_Generated.ScrollbarHorizontalHandleBorderRadius); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalHandleBorderRadius, value); } 
		}

		public float ScrollbarHorizontalHandleBorderSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalHandleBorderSize, DefaultStyleValues_Generated.ScrollbarHorizontalHandleBorderSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalHandleBorderSize, value); } 
		}

		public Color ScrollbarHorizontalHandleBorderColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarHorizontalHandleBorderColor, DefaultStyleValues_Generated.ScrollbarHorizontalHandleBorderColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarHorizontalHandleBorderColor, value); } 
		}

		public Texture2D ScrollbarHorizontalHandleImage {
			[DebuggerStepThrough] get { return (Texture2D)ReadObjectProperty(StylePropertyId.ScrollbarHorizontalHandleImage, DefaultStyleValues_Generated.ScrollbarHorizontalHandleImage); }
			internal set { WriteObjectProperty(StylePropertyId.ScrollbarHorizontalHandleImage, value); } 
		}

		public Color ScrollbarHorizontalHandleColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarHorizontalHandleColor, DefaultStyleValues_Generated.ScrollbarHorizontalHandleColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarHorizontalHandleColor, value); } 
		}

		public float ScrollbarHorizontalIncrementSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalIncrementSize, DefaultStyleValues_Generated.ScrollbarHorizontalIncrementSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalIncrementSize, value); } 
		}

		public float ScrollbarHorizontalIncrementBorderRadius {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalIncrementBorderRadius, DefaultStyleValues_Generated.ScrollbarHorizontalIncrementBorderRadius); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalIncrementBorderRadius, value); } 
		}

		public float ScrollbarHorizontalIncrementBorderSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalIncrementBorderSize, DefaultStyleValues_Generated.ScrollbarHorizontalIncrementBorderSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalIncrementBorderSize, value); } 
		}

		public Color ScrollbarHorizontalIncrementBorderColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarHorizontalIncrementBorderColor, DefaultStyleValues_Generated.ScrollbarHorizontalIncrementBorderColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarHorizontalIncrementBorderColor, value); } 
		}

		public Texture2D ScrollbarHorizontalIncrementImage {
			[DebuggerStepThrough] get { return (Texture2D)ReadObjectProperty(StylePropertyId.ScrollbarHorizontalIncrementImage, DefaultStyleValues_Generated.ScrollbarHorizontalIncrementImage); }
			internal set { WriteObjectProperty(StylePropertyId.ScrollbarHorizontalIncrementImage, value); } 
		}

		public Color ScrollbarHorizontalIncrementColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarHorizontalIncrementColor, DefaultStyleValues_Generated.ScrollbarHorizontalIncrementColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarHorizontalIncrementColor, value); } 
		}

		public float ScrollbarHorizontalDecrementSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalDecrementSize, DefaultStyleValues_Generated.ScrollbarHorizontalDecrementSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalDecrementSize, value); } 
		}

		public float ScrollbarHorizontalDecrementBorderRadius {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalDecrementBorderRadius, DefaultStyleValues_Generated.ScrollbarHorizontalDecrementBorderRadius); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalDecrementBorderRadius, value); } 
		}

		public float ScrollbarHorizontalDecrementBorderSize {
			[DebuggerStepThrough] get { return ReadFloatProperty(StylePropertyId.ScrollbarHorizontalDecrementBorderSize, DefaultStyleValues_Generated.ScrollbarHorizontalDecrementBorderSize); }
			internal set { WriteFloatProperty(StylePropertyId.ScrollbarHorizontalDecrementBorderSize, value); } 
		}

		public Color ScrollbarHorizontalDecrementBorderColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarHorizontalDecrementBorderColor, DefaultStyleValues_Generated.ScrollbarHorizontalDecrementBorderColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarHorizontalDecrementBorderColor, value); } 
		}

		public Texture2D ScrollbarHorizontalDecrementImage {
			[DebuggerStepThrough] get { return (Texture2D)ReadObjectProperty(StylePropertyId.ScrollbarHorizontalDecrementImage, DefaultStyleValues_Generated.ScrollbarHorizontalDecrementImage); }
			internal set { WriteObjectProperty(StylePropertyId.ScrollbarHorizontalDecrementImage, value); } 
		}

		public Color ScrollbarHorizontalDecrementColor {
			[DebuggerStepThrough] get { return ReadColorProperty(StylePropertyId.ScrollbarHorizontalDecrementColor, DefaultStyleValues_Generated.ScrollbarHorizontalDecrementColor); }
			internal set { WriteColorProperty(StylePropertyId.ScrollbarHorizontalDecrementColor, value); } 
		}

		internal void SetProperty(StyleProperty property) {
			switch(property.propertyId) {
				case StylePropertyId.OverflowX:
					OverflowX = property.IsDefined ? property.AsOverflow : DefaultStyleValues_Generated.OverflowX;
					break;
				case StylePropertyId.OverflowY:
					OverflowY = property.IsDefined ? property.AsOverflow : DefaultStyleValues_Generated.OverflowY;
					break;
				case StylePropertyId.BorderColor:
					BorderColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.BorderColor;
					break;
				case StylePropertyId.BackgroundColor:
					BackgroundColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.BackgroundColor;
					break;
				case StylePropertyId.BackgroundColorSecondary:
					BackgroundColorSecondary = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.BackgroundColorSecondary;
					break;
				case StylePropertyId.BackgroundImage:
					BackgroundImage = property.IsDefined ? property.AsTexture2D : DefaultStyleValues_Generated.BackgroundImage;
					break;
				case StylePropertyId.BackgroundImage1:
					BackgroundImage1 = property.IsDefined ? property.AsTexture2D : DefaultStyleValues_Generated.BackgroundImage1;
					break;
				case StylePropertyId.BackgroundImage2:
					BackgroundImage2 = property.IsDefined ? property.AsTexture2D : DefaultStyleValues_Generated.BackgroundImage2;
					break;
				case StylePropertyId.BackgroundGradientType:
					BackgroundGradientType = property.IsDefined ? property.AsGradientType : DefaultStyleValues_Generated.BackgroundGradientType;
					break;
				case StylePropertyId.BackgroundGradientAxis:
					BackgroundGradientAxis = property.IsDefined ? property.AsGradientAxis : DefaultStyleValues_Generated.BackgroundGradientAxis;
					break;
				case StylePropertyId.BackgroundGradientStart:
					BackgroundGradientStart = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.BackgroundGradientStart;
					break;
				case StylePropertyId.BackgroundFillRotation:
					BackgroundFillRotation = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.BackgroundFillRotation;
					break;
				case StylePropertyId.BackgroundFillType:
					BackgroundFillType = property.IsDefined ? property.AsBackgroundFillType : DefaultStyleValues_Generated.BackgroundFillType;
					break;
				case StylePropertyId.BackgroundShapeType:
					BackgroundShapeType = property.IsDefined ? property.AsBackgroundShapeType : DefaultStyleValues_Generated.BackgroundShapeType;
					break;
				case StylePropertyId.BackgroundFillOffsetX:
					BackgroundFillOffsetX = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.BackgroundFillOffsetX;
					break;
				case StylePropertyId.BackgroundFillOffsetY:
					BackgroundFillOffsetY = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.BackgroundFillOffsetY;
					break;
				case StylePropertyId.BackgroundFillScaleX:
					BackgroundFillScaleX = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.BackgroundFillScaleX;
					break;
				case StylePropertyId.BackgroundFillScaleY:
					BackgroundFillScaleY = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.BackgroundFillScaleY;
					break;
				case StylePropertyId.FlexItemOrder:
					FlexItemOrder = property.IsDefined ? property.AsInt : DefaultStyleValues_Generated.FlexItemOrder;
					break;
				case StylePropertyId.FlexItemGrow:
					FlexItemGrow = property.IsDefined ? property.AsInt : DefaultStyleValues_Generated.FlexItemGrow;
					break;
				case StylePropertyId.FlexItemShrink:
					FlexItemShrink = property.IsDefined ? property.AsInt : DefaultStyleValues_Generated.FlexItemShrink;
					break;
				case StylePropertyId.FlexItemSelfAlignment:
					FlexItemSelfAlignment = property.IsDefined ? property.AsCrossAxisAlignment : DefaultStyleValues_Generated.FlexItemSelfAlignment;
					break;
				case StylePropertyId.FlexLayoutDirection:
					FlexLayoutDirection = property.IsDefined ? property.AsLayoutDirection : DefaultStyleValues_Generated.FlexLayoutDirection;
					break;
				case StylePropertyId.FlexLayoutWrap:
					FlexLayoutWrap = property.IsDefined ? property.AsLayoutWrap : DefaultStyleValues_Generated.FlexLayoutWrap;
					break;
				case StylePropertyId.FlexLayoutMainAxisAlignment:
					FlexLayoutMainAxisAlignment = property.IsDefined ? property.AsMainAxisAlignment : DefaultStyleValues_Generated.FlexLayoutMainAxisAlignment;
					break;
				case StylePropertyId.FlexLayoutCrossAxisAlignment:
					FlexLayoutCrossAxisAlignment = property.IsDefined ? property.AsCrossAxisAlignment : DefaultStyleValues_Generated.FlexLayoutCrossAxisAlignment;
					break;
				case StylePropertyId.GridItemColStart:
					GridItemColStart = property.IsDefined ? property.AsInt : DefaultStyleValues_Generated.GridItemColStart;
					break;
				case StylePropertyId.GridItemColSpan:
					GridItemColSpan = property.IsDefined ? property.AsInt : DefaultStyleValues_Generated.GridItemColSpan;
					break;
				case StylePropertyId.GridItemRowStart:
					GridItemRowStart = property.IsDefined ? property.AsInt : DefaultStyleValues_Generated.GridItemRowStart;
					break;
				case StylePropertyId.GridItemRowSpan:
					GridItemRowSpan = property.IsDefined ? property.AsInt : DefaultStyleValues_Generated.GridItemRowSpan;
					break;
				case StylePropertyId.GridItemColSelfAlignment:
					GridItemColSelfAlignment = property.IsDefined ? property.AsCrossAxisAlignment : DefaultStyleValues_Generated.GridItemColSelfAlignment;
					break;
				case StylePropertyId.GridItemRowSelfAlignment:
					GridItemRowSelfAlignment = property.IsDefined ? property.AsCrossAxisAlignment : DefaultStyleValues_Generated.GridItemRowSelfAlignment;
					break;
				case StylePropertyId.GridLayoutDirection:
					GridLayoutDirection = property.IsDefined ? property.AsLayoutDirection : DefaultStyleValues_Generated.GridLayoutDirection;
					break;
				case StylePropertyId.GridLayoutDensity:
					GridLayoutDensity = property.IsDefined ? property.AsGridLayoutDensity : DefaultStyleValues_Generated.GridLayoutDensity;
					break;
				case StylePropertyId.GridLayoutColTemplate:
					GridLayoutColTemplate = property.IsDefined ? property.AsGridTemplate : DefaultStyleValues_Generated.GridLayoutColTemplate;
					break;
				case StylePropertyId.GridLayoutRowTemplate:
					GridLayoutRowTemplate = property.IsDefined ? property.AsGridTemplate : DefaultStyleValues_Generated.GridLayoutRowTemplate;
					break;
				case StylePropertyId.GridLayoutColAutoSize:
					GridLayoutColAutoSize = property.IsDefined ? property.AsGridTrackSize : DefaultStyleValues_Generated.GridLayoutColAutoSize;
					break;
				case StylePropertyId.GridLayoutRowAutoSize:
					GridLayoutRowAutoSize = property.IsDefined ? property.AsGridTrackSize : DefaultStyleValues_Generated.GridLayoutRowAutoSize;
					break;
				case StylePropertyId.GridLayoutColGap:
					GridLayoutColGap = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.GridLayoutColGap;
					break;
				case StylePropertyId.GridLayoutRowGap:
					GridLayoutRowGap = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.GridLayoutRowGap;
					break;
				case StylePropertyId.GridLayoutColAlignment:
					GridLayoutColAlignment = property.IsDefined ? property.AsCrossAxisAlignment : DefaultStyleValues_Generated.GridLayoutColAlignment;
					break;
				case StylePropertyId.GridLayoutRowAlignment:
					GridLayoutRowAlignment = property.IsDefined ? property.AsCrossAxisAlignment : DefaultStyleValues_Generated.GridLayoutRowAlignment;
					break;
				case StylePropertyId.MinWidth:
					MinWidth = property.IsDefined ? property.AsUIMeasurement : DefaultStyleValues_Generated.MinWidth;
					break;
				case StylePropertyId.MaxWidth:
					MaxWidth = property.IsDefined ? property.AsUIMeasurement : DefaultStyleValues_Generated.MaxWidth;
					break;
				case StylePropertyId.PreferredWidth:
					PreferredWidth = property.IsDefined ? property.AsUIMeasurement : DefaultStyleValues_Generated.PreferredWidth;
					break;
				case StylePropertyId.MinHeight:
					MinHeight = property.IsDefined ? property.AsUIMeasurement : DefaultStyleValues_Generated.MinHeight;
					break;
				case StylePropertyId.MaxHeight:
					MaxHeight = property.IsDefined ? property.AsUIMeasurement : DefaultStyleValues_Generated.MaxHeight;
					break;
				case StylePropertyId.PreferredHeight:
					PreferredHeight = property.IsDefined ? property.AsUIMeasurement : DefaultStyleValues_Generated.PreferredHeight;
					break;
				case StylePropertyId.MarginTop:
					MarginTop = property.IsDefined ? property.AsUIMeasurement : DefaultStyleValues_Generated.MarginTop;
					break;
				case StylePropertyId.MarginRight:
					MarginRight = property.IsDefined ? property.AsUIMeasurement : DefaultStyleValues_Generated.MarginRight;
					break;
				case StylePropertyId.MarginBottom:
					MarginBottom = property.IsDefined ? property.AsUIMeasurement : DefaultStyleValues_Generated.MarginBottom;
					break;
				case StylePropertyId.MarginLeft:
					MarginLeft = property.IsDefined ? property.AsUIMeasurement : DefaultStyleValues_Generated.MarginLeft;
					break;
				case StylePropertyId.BorderTop:
					BorderTop = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.BorderTop;
					break;
				case StylePropertyId.BorderRight:
					BorderRight = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.BorderRight;
					break;
				case StylePropertyId.BorderBottom:
					BorderBottom = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.BorderBottom;
					break;
				case StylePropertyId.BorderLeft:
					BorderLeft = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.BorderLeft;
					break;
				case StylePropertyId.BorderRadiusTopLeft:
					BorderRadiusTopLeft = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.BorderRadiusTopLeft;
					break;
				case StylePropertyId.BorderRadiusTopRight:
					BorderRadiusTopRight = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.BorderRadiusTopRight;
					break;
				case StylePropertyId.BorderRadiusBottomRight:
					BorderRadiusBottomRight = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.BorderRadiusBottomRight;
					break;
				case StylePropertyId.BorderRadiusBottomLeft:
					BorderRadiusBottomLeft = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.BorderRadiusBottomLeft;
					break;
				case StylePropertyId.PaddingTop:
					PaddingTop = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.PaddingTop;
					break;
				case StylePropertyId.PaddingRight:
					PaddingRight = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.PaddingRight;
					break;
				case StylePropertyId.PaddingBottom:
					PaddingBottom = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.PaddingBottom;
					break;
				case StylePropertyId.PaddingLeft:
					PaddingLeft = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.PaddingLeft;
					break;
				case StylePropertyId.TextColor:
					TextColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.TextColor;
					break;
				case StylePropertyId.TextFontAsset:
					TextFontAsset = property.IsDefined ? property.AsFont : DefaultStyleValues_Generated.TextFontAsset;
					break;
				case StylePropertyId.TextFontSize:
					TextFontSize = property.IsDefined ? property.AsInt : DefaultStyleValues_Generated.TextFontSize;
					break;
				case StylePropertyId.TextFontStyle:
					TextFontStyle = property.IsDefined ? property.AsFontStyle : DefaultStyleValues_Generated.TextFontStyle;
					break;
				case StylePropertyId.TextAlignment:
					TextAlignment = property.IsDefined ? property.AsTextAlignment : DefaultStyleValues_Generated.TextAlignment;
					break;
				case StylePropertyId.TextTransform:
					TextTransform = property.IsDefined ? property.AsTextTransform : DefaultStyleValues_Generated.TextTransform;
					break;
				case StylePropertyId.AnchorTop:
					AnchorTop = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.AnchorTop;
					break;
				case StylePropertyId.AnchorRight:
					AnchorRight = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.AnchorRight;
					break;
				case StylePropertyId.AnchorBottom:
					AnchorBottom = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.AnchorBottom;
					break;
				case StylePropertyId.AnchorLeft:
					AnchorLeft = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.AnchorLeft;
					break;
				case StylePropertyId.AnchorTarget:
					AnchorTarget = property.IsDefined ? property.AsAnchorTarget : DefaultStyleValues_Generated.AnchorTarget;
					break;
				case StylePropertyId.TransformPositionX:
					TransformPositionX = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.TransformPositionX;
					break;
				case StylePropertyId.TransformPositionY:
					TransformPositionY = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.TransformPositionY;
					break;
				case StylePropertyId.TransformPivotX:
					TransformPivotX = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.TransformPivotX;
					break;
				case StylePropertyId.TransformPivotY:
					TransformPivotY = property.IsDefined ? property.AsUIFixedLength : DefaultStyleValues_Generated.TransformPivotY;
					break;
				case StylePropertyId.TransformScaleX:
					TransformScaleX = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.TransformScaleX;
					break;
				case StylePropertyId.TransformScaleY:
					TransformScaleY = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.TransformScaleY;
					break;
				case StylePropertyId.TransformRotation:
					TransformRotation = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.TransformRotation;
					break;
				case StylePropertyId.TransformBehaviorX:
					TransformBehaviorX = property.IsDefined ? property.AsTransformBehavior : DefaultStyleValues_Generated.TransformBehaviorX;
					break;
				case StylePropertyId.TransformBehaviorY:
					TransformBehaviorY = property.IsDefined ? property.AsTransformBehavior : DefaultStyleValues_Generated.TransformBehaviorY;
					break;
				case StylePropertyId.LayoutType:
					LayoutType = property.IsDefined ? property.AsLayoutType : DefaultStyleValues_Generated.LayoutType;
					break;
				case StylePropertyId.LayoutBehavior:
					LayoutBehavior = property.IsDefined ? property.AsLayoutBehavior : DefaultStyleValues_Generated.LayoutBehavior;
					break;
				case StylePropertyId.ZIndex:
					ZIndex = property.IsDefined ? property.AsInt : DefaultStyleValues_Generated.ZIndex;
					break;
				case StylePropertyId.RenderLayerOffset:
					RenderLayerOffset = property.IsDefined ? property.AsInt : DefaultStyleValues_Generated.RenderLayerOffset;
					break;
				case StylePropertyId.RenderLayer:
					RenderLayer = property.IsDefined ? property.AsRenderLayer : DefaultStyleValues_Generated.RenderLayer;
					break;
				case StylePropertyId.ScrollbarVerticalAttachment:
					ScrollbarVerticalAttachment = property.IsDefined ? property.AsVerticalScrollbarAttachment : DefaultStyleValues_Generated.ScrollbarVerticalAttachment;
					break;
				case StylePropertyId.ScrollbarVerticalButtonPlacement:
					ScrollbarVerticalButtonPlacement = property.IsDefined ? property.AsScrollbarButtonPlacement : DefaultStyleValues_Generated.ScrollbarVerticalButtonPlacement;
					break;
				case StylePropertyId.ScrollbarVerticalTrackSize:
					ScrollbarVerticalTrackSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalTrackSize;
					break;
				case StylePropertyId.ScrollbarVerticalTrackBorderRadius:
					ScrollbarVerticalTrackBorderRadius = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalTrackBorderRadius;
					break;
				case StylePropertyId.ScrollbarVerticalTrackBorderSize:
					ScrollbarVerticalTrackBorderSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalTrackBorderSize;
					break;
				case StylePropertyId.ScrollbarVerticalTrackBorderColor:
					ScrollbarVerticalTrackBorderColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarVerticalTrackBorderColor;
					break;
				case StylePropertyId.ScrollbarVerticalTrackImage:
					ScrollbarVerticalTrackImage = property.IsDefined ? property.AsTexture2D : DefaultStyleValues_Generated.ScrollbarVerticalTrackImage;
					break;
				case StylePropertyId.ScrollbarVerticalTrackColor:
					ScrollbarVerticalTrackColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarVerticalTrackColor;
					break;
				case StylePropertyId.ScrollbarVerticalHandleSize:
					ScrollbarVerticalHandleSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalHandleSize;
					break;
				case StylePropertyId.ScrollbarVerticalHandleBorderRadius:
					ScrollbarVerticalHandleBorderRadius = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalHandleBorderRadius;
					break;
				case StylePropertyId.ScrollbarVerticalHandleBorderSize:
					ScrollbarVerticalHandleBorderSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalHandleBorderSize;
					break;
				case StylePropertyId.ScrollbarVerticalHandleBorderColor:
					ScrollbarVerticalHandleBorderColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarVerticalHandleBorderColor;
					break;
				case StylePropertyId.ScrollbarVerticalHandleImage:
					ScrollbarVerticalHandleImage = property.IsDefined ? property.AsTexture2D : DefaultStyleValues_Generated.ScrollbarVerticalHandleImage;
					break;
				case StylePropertyId.ScrollbarVerticalHandleColor:
					ScrollbarVerticalHandleColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarVerticalHandleColor;
					break;
				case StylePropertyId.ScrollbarVerticalIncrementSize:
					ScrollbarVerticalIncrementSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalIncrementSize;
					break;
				case StylePropertyId.ScrollbarVerticalIncrementBorderRadius:
					ScrollbarVerticalIncrementBorderRadius = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalIncrementBorderRadius;
					break;
				case StylePropertyId.ScrollbarVerticalIncrementBorderSize:
					ScrollbarVerticalIncrementBorderSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalIncrementBorderSize;
					break;
				case StylePropertyId.ScrollbarVerticalIncrementBorderColor:
					ScrollbarVerticalIncrementBorderColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarVerticalIncrementBorderColor;
					break;
				case StylePropertyId.ScrollbarVerticalIncrementImage:
					ScrollbarVerticalIncrementImage = property.IsDefined ? property.AsTexture2D : DefaultStyleValues_Generated.ScrollbarVerticalIncrementImage;
					break;
				case StylePropertyId.ScrollbarVerticalIncrementColor:
					ScrollbarVerticalIncrementColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarVerticalIncrementColor;
					break;
				case StylePropertyId.ScrollbarVerticalDecrementSize:
					ScrollbarVerticalDecrementSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalDecrementSize;
					break;
				case StylePropertyId.ScrollbarVerticalDecrementBorderRadius:
					ScrollbarVerticalDecrementBorderRadius = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalDecrementBorderRadius;
					break;
				case StylePropertyId.ScrollbarVerticalDecrementBorderSize:
					ScrollbarVerticalDecrementBorderSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarVerticalDecrementBorderSize;
					break;
				case StylePropertyId.ScrollbarVerticalDecrementBorderColor:
					ScrollbarVerticalDecrementBorderColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarVerticalDecrementBorderColor;
					break;
				case StylePropertyId.ScrollbarVerticalDecrementImage:
					ScrollbarVerticalDecrementImage = property.IsDefined ? property.AsTexture2D : DefaultStyleValues_Generated.ScrollbarVerticalDecrementImage;
					break;
				case StylePropertyId.ScrollbarVerticalDecrementColor:
					ScrollbarVerticalDecrementColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarVerticalDecrementColor;
					break;
				case StylePropertyId.ScrollbarHorizontalAttachment:
					ScrollbarHorizontalAttachment = property.IsDefined ? property.AsHorizontalScrollbarAttachment : DefaultStyleValues_Generated.ScrollbarHorizontalAttachment;
					break;
				case StylePropertyId.ScrollbarHorizontalButtonPlacement:
					ScrollbarHorizontalButtonPlacement = property.IsDefined ? property.AsScrollbarButtonPlacement : DefaultStyleValues_Generated.ScrollbarHorizontalButtonPlacement;
					break;
				case StylePropertyId.ScrollbarHorizontalTrackSize:
					ScrollbarHorizontalTrackSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalTrackSize;
					break;
				case StylePropertyId.ScrollbarHorizontalTrackBorderRadius:
					ScrollbarHorizontalTrackBorderRadius = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalTrackBorderRadius;
					break;
				case StylePropertyId.ScrollbarHorizontalTrackBorderSize:
					ScrollbarHorizontalTrackBorderSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalTrackBorderSize;
					break;
				case StylePropertyId.ScrollbarHorizontalTrackBorderColor:
					ScrollbarHorizontalTrackBorderColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarHorizontalTrackBorderColor;
					break;
				case StylePropertyId.ScrollbarHorizontalTrackImage:
					ScrollbarHorizontalTrackImage = property.IsDefined ? property.AsTexture2D : DefaultStyleValues_Generated.ScrollbarHorizontalTrackImage;
					break;
				case StylePropertyId.ScrollbarHorizontalTrackColor:
					ScrollbarHorizontalTrackColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarHorizontalTrackColor;
					break;
				case StylePropertyId.ScrollbarHorizontalHandleSize:
					ScrollbarHorizontalHandleSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalHandleSize;
					break;
				case StylePropertyId.ScrollbarHorizontalHandleBorderRadius:
					ScrollbarHorizontalHandleBorderRadius = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalHandleBorderRadius;
					break;
				case StylePropertyId.ScrollbarHorizontalHandleBorderSize:
					ScrollbarHorizontalHandleBorderSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalHandleBorderSize;
					break;
				case StylePropertyId.ScrollbarHorizontalHandleBorderColor:
					ScrollbarHorizontalHandleBorderColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarHorizontalHandleBorderColor;
					break;
				case StylePropertyId.ScrollbarHorizontalHandleImage:
					ScrollbarHorizontalHandleImage = property.IsDefined ? property.AsTexture2D : DefaultStyleValues_Generated.ScrollbarHorizontalHandleImage;
					break;
				case StylePropertyId.ScrollbarHorizontalHandleColor:
					ScrollbarHorizontalHandleColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarHorizontalHandleColor;
					break;
				case StylePropertyId.ScrollbarHorizontalIncrementSize:
					ScrollbarHorizontalIncrementSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalIncrementSize;
					break;
				case StylePropertyId.ScrollbarHorizontalIncrementBorderRadius:
					ScrollbarHorizontalIncrementBorderRadius = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalIncrementBorderRadius;
					break;
				case StylePropertyId.ScrollbarHorizontalIncrementBorderSize:
					ScrollbarHorizontalIncrementBorderSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalIncrementBorderSize;
					break;
				case StylePropertyId.ScrollbarHorizontalIncrementBorderColor:
					ScrollbarHorizontalIncrementBorderColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarHorizontalIncrementBorderColor;
					break;
				case StylePropertyId.ScrollbarHorizontalIncrementImage:
					ScrollbarHorizontalIncrementImage = property.IsDefined ? property.AsTexture2D : DefaultStyleValues_Generated.ScrollbarHorizontalIncrementImage;
					break;
				case StylePropertyId.ScrollbarHorizontalIncrementColor:
					ScrollbarHorizontalIncrementColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarHorizontalIncrementColor;
					break;
				case StylePropertyId.ScrollbarHorizontalDecrementSize:
					ScrollbarHorizontalDecrementSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalDecrementSize;
					break;
				case StylePropertyId.ScrollbarHorizontalDecrementBorderRadius:
					ScrollbarHorizontalDecrementBorderRadius = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalDecrementBorderRadius;
					break;
				case StylePropertyId.ScrollbarHorizontalDecrementBorderSize:
					ScrollbarHorizontalDecrementBorderSize = property.IsDefined ? property.AsFloat : DefaultStyleValues_Generated.ScrollbarHorizontalDecrementBorderSize;
					break;
				case StylePropertyId.ScrollbarHorizontalDecrementBorderColor:
					ScrollbarHorizontalDecrementBorderColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarHorizontalDecrementBorderColor;
					break;
				case StylePropertyId.ScrollbarHorizontalDecrementImage:
					ScrollbarHorizontalDecrementImage = property.IsDefined ? property.AsTexture2D : DefaultStyleValues_Generated.ScrollbarHorizontalDecrementImage;
					break;
				case StylePropertyId.ScrollbarHorizontalDecrementColor:
					ScrollbarHorizontalDecrementColor = property.IsDefined ? property.AsColor : DefaultStyleValues_Generated.ScrollbarHorizontalDecrementColor;
					break;
				default: throw new ArgumentOutOfRangeException(nameof(property.propertyId), property.propertyId, null);
}				} 
}
}